# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9de2d34b3efb3572227dc95b83249fd54df47f9b734962bcc6ab5e5b385009bb25c077065c730e4fecb5a0c73e649b815f5b07be37cad7656eb87dc9cfe43849

test:
  secret_key_base: 82e13e3f23b0c8c75cfc010b4153c257a43d6ba427eb627ad461c284a0f9212381324ef88d44fcc92c59f8b1c9c638a089999820afed99bfc51a002d002b8f95

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
